[workspace]
members = [
    "d_same_differences",
    "c_move_brackets",
    "c_kth_not_divisible_by_n",
    "a_odd_divisor",
    "a_hit_the_lottery",
    "a_divisibility_problem",
    "main",
    "algo_lib",
]
resolver = "2"
