[workspace]
members = [
    "e_special_elements",
    "d_pair_of_topics",
    "c_product_of_three_numbers",
    "b_same_parity_summands",
    "a_nastia_and_nearly_good_numbers",
    "c_alternating_subsequence",
    "d_same_differences",
    "c_move_brackets",
    "c_kth_not_divisible_by_n",
    "a_odd_divisor",
    "a_hit_the_lottery",
    "a_divisibility_problem",
    "main",
    "algo_lib",
]
resolver = "2"
